# SC1090: file sourcing   - shellcheck is unaware of sourced pkgfiles
# SC2154: undeclared vars - shellcheck is unaware vars inside pkgfiles
# SC2034: unused variables - shellcheck is unaware of pkgfile vars use
script:
  - make
  - shellcheck -s sh -e 1090 -e 2154 bonsai
  - shellcheck -s sh -e 1090 -e 2154 tools/*
  - shellcheck -s sh -e 1090 -e 2154 -e 2034 ports/*/*/pkgfile
