# SC1090: file sourcing     -  we know, pkgfiles
# SC2154: undeclared vars   -  vars inside pkgfiles
# SC2046: word splitting    -  this is done sparingly and intentionally
# SC2144: globs with test   -  intentional, it works in this instance
script:
  - shellcheck -s sh -e 1090 -e 2154 -e 2046 -e 2144 bonsai
  - shellcheck -s sh -e 1090 -e 2154 -e 2046 -e 2144 tools/mksum
