#!/bin/sh
#
# perform a search of all libraries for a given symbol
#

case "$1" in
    -h|--help)
        >&2 echo 'Usage: nmsearch [path] symbol'
        exit
esac

[ -d "$1" ] && { path="$1" ; shift ; } || path=/lib

[ "$1" ] || exit 1

find "$path" -name '*.a' | while read -r lib ; do
    nm "$lib" 2>/dev/null | \
        grep -i ".* T $1" >/dev/null && \
        echo "$lib"
done
