#!/bin/sh
#
# http://github.com/bonsai-linux/tools
#
# dump a port skeleton to stdout
#

# note: Please delete unused functions
#       before submitting a PR, thanks
cat << 'EOF'
info=''
version=
source=
deps=
sha256=
prebuild() {
    :
}
build() {
    bonsai_configure
    bonsai_make
    bonsai_make install
}
postbuild() {
    :
}
EOF
